



# Offense count: 1
Lint/RescueException:
  Exclude:
    - 'app/controllers/tables_controller.rb'

# Offense count: 1
Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'app/helpers/menus_helper.rb'


# Offense count: 45
Lint/UselessAssignment:
  Exclude:
    - 'app/controllers/home_controller.rb'
    - 'app/controllers/tables_controller.rb'
    - 'app/helpers/tables_helper.rb'
    - 'db/seeds.rb'

# Offense count: 9
Metrics/AbcSize:
  Max: 43

# Offense count: 2
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 151

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 113

# Offense count: 13
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 28

# Offense count: 1
# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist, MethodDefinitionMacros.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
# MethodDefinitionMacros: define_method, define_singleton_method
Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'app/models/menu.rb'

# Offense count: 1
# Configuration parameters: AllowedChars.
Style/AsciiComments:
  Exclude:
    - 'app/models/menu.rb'

# Offense count: 59
Style/Documentation:
  Enabled: false


# Offense count: 2
# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'

# Offense count: 124
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: when_needed, always, never
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 2
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'app/controllers/manager/restaurant_tables_controller.rb'
    - 'app/controllers/tables_controller.rb'

# Offense count: 42
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  Exclude:
    - 'app/controllers/home_controller.rb'
    - 'app/controllers/manager/menus_controller.rb'
    - 'app/models/menu.rb'
    - 'app/models/restaurant.rb'
    - 'app/models/restaurant_table.rb'
    - 'app/models/table.rb'
    - 'db/migrate/20180905081021_add_translation_table.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/IfUnlessModifier:
  Exclude:
    - 'app/controllers/home_controller.rb'
    - 'app/controllers/manager/restaurant_tables_controller.rb'
    - 'app/controllers/tables_controller.rb'

# Offense count: 2
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: MinDigits, Strict.
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, EnforcedStyle, IgnoredMethods.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/tables_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/initializers/assets.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

# Offense count: 2
# Cop supports --auto-correct.
Style/RedundantConditional:
  Exclude:
    - 'app/helpers/menus_helper.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

# Offense count: 391
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: false

# Offense count: 22
# Cop supports --auto-correct.
# Configuration parameters: MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
# IgnoredMethods: respond_to, define_method
Style/SymbolProc:
  Exclude:
    - 'app/controllers/tables_controller.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInHashLiteral:
  Exclude:
    - 'app/controllers/home_controller.rb'
    - 'app/controllers/tables_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: percent
  MinSize: 5

# Offense count: 182
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 383
