inherit_from: .rubocop_todo.yml

Layout/AlignHash:
  Exclude:
    - 'db/seeds.rb'
Layout/ClosingParenthesisIndentation:
  Exclude:
    - 'db/seeds.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'
